version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Monta el código para desarrollo en caliente
      - ./data:/app/data  # Monta la carpeta para persistir la base SQLite
    environment:
      - DJANGO_SETTINGS_MODULE=task_manager.settings
    command: python manage.py runserver 0.0.0.0:8000
